// <auto-generated />
using System;
using ConferenceRooms.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceRooms.Data.Persistence.Migrations
{
    [DbContext(typeof(ConferenceRoomsDbContext))]
    [Migration("20260825123518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("ConferenceRooms.Business.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RoomCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RoomRateSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "StartUtc", "EndUtc");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.BookingOptionalService", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionalServiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId", "OptionalServiceId");

                    b.HasIndex("OptionalServiceId");

                    b.ToTable("BookingOptionalServices", (string)null);
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.OptionalService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OptionalServices", (string)null);
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.RoomOptionalService", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionalServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId", "OptionalServiceId");

                    b.HasIndex("OptionalServiceId");

                    b.ToTable("RoomOptionalServices", (string)null);
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.Booking", b =>
                {
                    b.HasOne("ConferenceRooms.Business.Domain.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.BookingOptionalService", b =>
                {
                    b.HasOne("ConferenceRooms.Business.Domain.Booking", "Booking")
                        .WithMany("SelectedServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRooms.Business.Domain.OptionalService", null)
                        .WithMany()
                        .HasForeignKey("OptionalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.RoomOptionalService", b =>
                {
                    b.HasOne("ConferenceRooms.Business.Domain.OptionalService", "OptionalService")
                        .WithMany()
                        .HasForeignKey("OptionalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConferenceRooms.Business.Domain.Room", "Room")
                        .WithMany("SupportedServices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionalService");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.Booking", b =>
                {
                    b.Navigation("SelectedServices");
                });

            modelBuilder.Entity("ConferenceRooms.Business.Domain.Room", b =>
                {
                    b.Navigation("SupportedServices");
                });
#pragma warning restore 612, 618
        }
    }
}
